version: '3'
services:
  aq-static:
    image: svelte-docker-static

    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-static
    ports:
      - 3000:80

  aq-node:
    image: svelte-docker-node

    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-node
    ports:
      - 3000:3000